- name: Clean reproducer layout
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: true
  tasks:
    - name: Call reproducer.cleanup
      tags:
        - deepscrub
      ansible.builtin.import_role:
        name: reproducer
        tasks_from: cleanup.yml

    - name: Clean up devscripts related content
      tags:
        - never
        - deepscrub
      ansible.builtin.import_role:
        name: devscripts
        tasks_from: cleanup.yml

    - name: Clean up CRC related content
      tags:
        - never
        - deepscrub
      ansible.builtin.import_role:
        name: rhol_crc
        tasks_from: cleanup.yml

    - name: Clean up nat64 appliance
      tags:
        - never
        - deepscrub
      ansible.builtin.import_role:
        name: nat64_appliance
        tasks_from: cleanup.yml

    - name: Remove remote selected data directories
      tags:
        - deepscrub
      ansible.builtin.file:
        path: "{{ cifmw_reproducer_basedir }}/{{ item }}"
        state: absent
      loop:
        - reproducer-inventory
        - reproducer-network-env

    - name: Remove /etc/ci/ directory
      tags:
        - deepscrub
      become: true
      ansible.builtin.file:
        path: /etc/ci/
        state: absent

    - name: Remove local ci-reproducer data directory
      tags:
        - deepscrub
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/ci-framework-data/ci-reproducer"
        state: absent

    - name: Clean repo_setup content
      tags:
        - deepscrub
      ansible.builtin.import_role:
        name: "repo_setup"
        tasks_from: "clean_rhos_release.yml"

    - name: Clean ci_setup repositories
      tags:
        - deepscrub
      ansible.builtin.import_role:
        name: "ci_setup"
        tasks_from: "cleanup.yml"

    - name: Remove basedir
      tags:
        - never
        - deepscrub
      ansible.builtin.file:
        path: "{{ cifmw_reproducer_basedir }}"
        state: absent

    - name: Clear all facts
      tags:
        - deepscrub
      ansible.builtin.meta: clear_facts
