---
- name: Refresh oooq_pool before starting VMs
  when:
    - "item.value.status == 'running'"
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ item.key }}"
  loop: "{{ ansible_libvirt_pools | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Start VMs for type {{ vm_type }}"
  community.libvirt.virt:
    state: running
    name: "{{ cifmw_libvirt_manager_vm_prefix }}{{ vm_type }}{{ cifmw_libvirt_manager_vm_separator }}{{ vm_id }}"
    uri: "qemu:///system"
  loop: "{{ range(0, vm_data.value.amount | default(1) | int) }}"
  loop_control:
    index_var: vm_id
    label: "{{ vm_type }}{{ cifmw_libvirt_manager_vm_separator }}{{ vm_id }}"
