---
# Mainly used to override the defaults set in .config/molecule/
# By default, it uses the "config_podman.yml" - in CI, it will use
# "config_local.yml".


log: true

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        cifmw_devscripts_config_overrides_patch_01_override_br_management:
          manage_br_bridge: 'n'
