---
- name: Clean directories
  tags:
    - cleanup
  vars:
    directory_state: absent
  ansible.builtin.import_tasks: directories.yml

- name: Cleanup the repos
  tags:
    - cleanup
  vars:
    rhsm_repo_state: "disabled"
    yum_repo_state: "absent"
  ansible.builtin.import_tasks: repos.yml

- name: Clean EPEL
  tags:
    - cleanup
  vars:
    epel_status: absent
  ansible.builtin.import_tasks: epel.yml
