---
- hosts: "{{ cifmw_target_host | default('localhost') }}"
  tasks:
    - name: fail
      ansible.builtin.fail:
        msg: "Failing before touching nmcli"
    # jgilaber: we need to make sure nncp does not touch the vlans, otherwise
    # it'll create them with the same MAC address as the ospbr bridge and that
    # causes problems when trying to reach the dnsmasq service from the compute
    # node. Changing the interface and connnection name to what is used in the
    # nncp CR avoids the issue
    - name: Change vlan interface and connection names
      delegate_to: "crc"
      become: true
      ansible.builtin.shell: |
        nmcli con down ci-{{ item }}
        nmcli con modify ci-{{ item }} connection.interface-name {{ item }}
        nmcli con modify ci-{{ item }} connection.id {{ item }}
        nmcli con up {{ item }}
      loop:
        - internalapi
        - storage
        - tenant

- hosts: computes
  tasks:
    - name: Setup repos
      ansible.builtin.include_role:
        name: repo_setup

    - name: Set hostname to inventory hostname for ceph deployment
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: "systemd"
