---
- name: Create vlan chield interface
  gather_facts: false
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  tasks:
    - name: nmcli create vlan chield
      community.general.nmcli:
        conn_name: "{{ cifmw_interface_conn_name | default('osp_trunk.218') }}"
        vlandev: "{{ cifmw_interface_conn_name | default('osp_trunk.218') }}"
        type: vlan
        vlandev: "{{ cifmw_interface_master |  default('osp_trunk') }}"
        vlanid: "{{ cifmw_interface_vlanid | default(218) }}"
        ip4: "{{ cifmw_interface_ip4 | default('172.38.0.1/24') }}"
        state: present
      become: true
      delegate_to: "{{ cifmw_interface_host | default('hypervisor') }}"
